name: push-master

on:
  push:
    branches:
      - master

jobs:
  build_test_publish:
    name: Build, test, and publish unstable release
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [10.x]
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: "https://registry.npmjs.org"
            scope: "@mattrglobal"
        - run: yarn install --frozen-lockfile
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        - run: yarn lint
        - run: yarn build
        - run: yarn test
        - name: Publish unstable release
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: |
            git checkout master
            yarn install --frozen-lockfile
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc 2> /dev/null
            git config user.name "Mattr CI"
            git config user.email "ci@mattr.global"
            git status
            yarn publish:unstable